### ISSUE TITLE
Allow a stage to be associated with an API Gateway Usage Plan

### ISSUE THREAD

**Issue by szilveszter** [rackerlabs/yolo#15]
API keys in API Gateway have to be associated with Usage Plans, and these plans are associated with the different stages. In order to reduce manual steps needed to be taken, would it be possible to automatically associate the current stage being deployed with a usage plan (optionally).

I have something like this in mind:

```yaml
services:
  myService:
    type: 'lambda-apigateway'
    apigateway:
      - custom_domain: '{{ stage.outputs.CustomDomain }}'
        base_path: '/'
        rest_api_name: 'rms-caportal-api'
        # This below could also be a list to support multiple usage plans
        usage_plan: '{{ account.outputs.UsagePlanId }}'
```

This way the only manual step we need to take is to generate the actual API keys.
