### ISSUE TITLE
Move (default) region setting from stage & template config to account config

### ISSUE THREAD

**Issue by larsbutler** [rackerlabs/yolo#2]
It turns that it doesn't really makes sense to have regions specified in the `templates` and `stages` sections. However, in cases where we have many deployments of a service across multiple different accounts, it makes more sense to specify the default regions in the accounts definition.

Here's how the yolo file structure would change.

Before:

```yaml
accounts:
  - name: 'mydev'
    account_number: '111222333444'
  - name: 'myprod'
    account_number: '555666777888'

templates:
  account:
    path: 'cloudformation/account'
    params:
      AccountName: '{{ account.name }}'
    region: 'us-west-2'
  stage:
    path: 'cloudformation/stage'
    params:
      Stage: '{{ stage.name }}'
      AccountOutput: '{{ account.outputs.AccountOutput }}'
stages:
  default:
    account: 'mydev'
    region: 'us-west-2'
  dev:
    account: 'mydev'
    region: 'us-east-1'
  prod:
    account: 'myprod'
    region: 'us-west-2'
    protected: true
```

After:

```yaml
accounts:
  - name: 'mydev'
    account_number: '111222333444'
    default_region: 'us-east-1'
  - name: 'myprod'
    account_number: '555666777888'
    default_region: 'us-west-2'

templates:
  account:
    path: 'cloudformation/account'
    params:
      AccountName: '{{ account.name }}'
  stage:
    path: 'cloudformation/stage'
    params:
      Stage: '{{ stage.name }}'
      AccountOutput: '{{ account.outputs.AccountOutput }}'
stages:
  default:
    account: 'mydev'
    # In this case, we wouldn't support stage-specific regions.
    # This needs some thought and could be a future feature.
    # region: 'us-west-2'
  dev:
    account: 'mydev'
  prod:
    account: 'myprod'
    protected: true
```

```diff
 accounts:
   - name: 'mydev'
     account_number: '111222333444'
+    default_region: 'us-east-1'
   - name: 'myprod'
     account_number: '555666777888'
+    default_region: 'us-west-2'
 
 templates:
   account:
     path: 'cloudformation/account'
     params:
       AccountName: '{{ account.name }}'
-    region: 'us-west-2'
   stage:
     path: 'cloudformation/stage'
     params:
@@ -18,11 +19,11 @@
 stages:
   default:
     account: 'mydev'
-    region: 'us-west-2'
+    # In this case, we wouldn't support stage-specific regions.
+    # This needs some thought and could be a future feature.
+    # region: 'us-west-2'
   dev:
     account: 'mydev'
-    region: 'us-east-1'
   prod:
     account: 'myprod'
-    region: 'us-west-2'
     protected: true
```

(As an extension of this, it may be useful in the future to allow an optional `--region REGION` parameter for testing or experimentation, but this can wait.)
